import "./globals.css";
import { Prosto_One, Sora } from "next/font/google";
import { Navigation } from "@/components/Navigation";

const prosto = Prosto_One({ subsets: ["latin"], weight: ["400"] });
const sora = Sora({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata = {
  title: "Apptexlab Pvt Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sora.variable} ${prosto.variable}`}>
        <Navigation />
        <main>{children}</main>
      </body>
    </html>
  );
}
